#!/usr/bin/env php
<?php

$_ENV['HOME'] = getenv('HOME');
$_ENV['VAGRANT_DOTFILE_PATH'] = homestead_path().DIRECTORY_SEPARATOR.'.vagrant';

if (file_exists(__DIR__.'/vendor/autoload.php'))
{
	require __DIR__.'/vendor/autoload.php';
}
else
{
	require __DIR__.'/../../autoload.php';
}

function homestead_path()
{
	if (isset($_SERVER['HOME']))
	{
		return $_SERVER['HOME'].'/.homestead';
	}
	else
	{
		return $_SERVER['HOMEDRIVE'].$_SERVER['HOMEPATH'].DIRECTORY_SEPARATOR.'.homestead';
	}
}

$app = new Symfony\Component\Console\Application('Laravel Hsfork', '2.2.1');

$app->add(new Laravel\Hsfork\DestroyCommand);
$app->add(new Laravel\Hsfork\EditCommand);
$app->add(new Laravel\Hsfork\HaltCommand);
$app->add(new Laravel\Hsfork\InitCommand);
$app->add(new Laravel\Hsfork\ProvisionCommand);
$app->add(new Laravel\Hsfork\ResumeCommand);
$app->add(new Laravel\Hsfork\RunCommand);
$app->add(new Laravel\Hsfork\UpCommand);
$app->add(new Laravel\Hsfork\UpdateCommand);
$app->add(new Laravel\Hsfork\SshCommand);
$app->add(new Laravel\Hsfork\StatusCommand);
$app->add(new Laravel\Hsfork\SuspendCommand);

$app->run();
